satchboogie_guitar_markers_text_f356fc54 = qs("Head 1")
satchboogie_guitar_markers_text_45a37065 = qs("Solo A")
satchboogie_guitar_markers_text_dcaa21df = qs("Solo B")
satchboogie_guitar_markers_text_abad1149 = qs("Solo C")
satchboogie_guitar_markers_text_35c984ea = qs("Solo D")
satchboogie_guitar_markers_text_42ceb47c = qs("Solo E")
satchboogie_guitar_markers_text_dbc7e5c6 = qs("Solo F")
satchboogie_guitar_markers_text_6a5fadee = qs("Head 2")
